--- 
apiVersion: v1
kind: PersistentVolume
metadata: 
  labels: 
    type: local
  name: mongo-persistent-storage
spec: 
  accessModes: 
    - ReadWriteOnce
  capacity: 
    storage: 100Gi
  hostPath: 
    path: /var/lib/mongodb/data
