--- 
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: rocketchat-mongo
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: mongodb
  serviceName: mongodb-internal
  template: 
    metadata: 
      labels: 
        app: mongodb
    spec: 
      containers: 
        - 
          args: 
            - "--replSet"
            - rs0
          command: 
            - mongod
          env: 
            - 
              name: MONGODB_DATABASE
              value: mongodb
            - 
              name: MONGODB_USER
              value: mongodb_user
            - 
              name: MONGODB_PASSWORD
              value: mongodb_password
            - 
              name: MONGODB_ADMIN_PASSWORD
              value: mongodb_admin_password
            - 
              name: MONGODB_REPLICA_NAME
              value: rs0
            - 
              name: MONGODB_SERVICE_NAME
              value: mongodb-internal
          image: "registry.access.redhat.com/rhscl/mongodb-34-rhel7:latest"
          livenessProbe: 
            exec: 
              command: 
                - cat
                - /tmp/initialized
          name: mongodb
          ports: 
            - 
              containerPort: 27017
              name: mongodb
          volumeMounts: 
            - 
              mountPath: /var/lib/mongodb/data
              name: mongo-persistent-storage
      terminationGracePeriodSeconds: 10
  volumeClaimTemplates: 
    - 
      metadata: 
        name: mongo-persistent-storage
      spec: 
        accessModes: 
          - ReadWriteOnce
        resources: 
          requests: 
            storage: 100Gi
